import { Montserrat } from "next/font/google";
import "@/styles/base.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { PopupsProvider } from "@/context/PopupsContext";
import { CartProvider } from "@/context/CartContext";
import { SpeedInsights } from "@vercel/speed-insights/next";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Modellist Digital",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <SpeedInsights />
        <CartProvider>
          <PopupsProvider>
            <Header />
            <main>{children}</main>
            <Footer />
          </PopupsProvider>
        </CartProvider>
      </body>
    </html>
  );
}
